import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { SparklesCore } from "@/components/ui/sparkles";
// import { DottedGlowBackground } from "@/components/ui/dotted-glow-background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body
        className="min-h-screen relative flex flex-col items-center bg-dots"
      >

        <SparklesCore
          background="transparent"
          minSize={0.4}
          maxSize={1}
          particleDensity={100}
          className="w-full h-full absolute z-0"
          particleColor="#FFFFFF"
        />
        <Navbar />

        {children}

      </body>
    </html>
  );
}
