import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { SparklesCore } from "@/components/ui/sparkles";
import QueryProvider from "./components/providers/queryProvider";
// import { DottedGlowBackground } from "@/components/ui/dotted-glow-background";
import toast, { Toaster } from 'react-hot-toast';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body
        className="min-h-full relative flex flex-col items-center bg-dots p-0 m-0"
      >

        <SparklesCore
          background="transparent"
          minSize={0.4}
          maxSize={1}
          particleDensity={100}
          className="w-full h-full absolute z-0"
          particleColor="#FFFFFF"
        />
        <Navbar />
        <QueryProvider>
          
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
